### ISSUE TITLE
Very slow startup

### ISSUE THREAD

**Issue by aagha** [starlight/swan-desktop#23] opened 2017-03-28 04:58 UTC
Hi - When I launch Swan Xfce4 Desktop, the window opens and closes very quickly.

How do I debug the issue?

**Comment by isaacwhanson** [comment] 2017-03-28 12:13
Look in `var/log/xwin` and ~/.xsession-errors` . Post here if you need further help

**Comment by aagha** [comment] 2017-03-28 15:44
Neither of those exist. :-(

**Comment by isaacwhanson** [comment] 2017-03-28 16:28
Try running `startxfce4` in Swan Console.  You should at least be able to see the X output that way.

**Comment by aagha** [comment] 2017-03-28 16:59
The Swan Console isn't launching.

I double-click the desktop icon called, "Swan Xfce4 Desktop" and the window flashes open and then closes.

I've tracked down the setup.log (it's large). Can I paste it somehwere for you to look at? Where?

**Comment by aagha** [comment] 2017-03-28 17:18
Error: 

(xfce4-session:5760): xfce4-session-WARNING **: xfsm_manager_load_session: Something wrong with /cygdrive/c/cygwin/home/amagha//.cache/sessions/xfce4-session-METRICAL#0, Does it exist? Permissions issue?

(gnome-keyring-daemon:12452): GLib-GIO-WARNING **: Problems looking up entry in keyring: Error opening keyring '/cygdrive/c/cygwin/home/amagha/.dbus-keyrings/org_freedesktop_general' for reading: Failed to open file '/cygdrive/c/cygwin/home/amagha/.dbus-keyrings/org_freedesktop_general': No such file or directory

**Comment by isaacwhanson** [comment] 2017-03-28 21:14
Those messages are normal, just warnings.  xfce4-session and gnome-keyring produce those messages right before creating your session and keyring.

I wonder how long you are waiting for it to start up before interrupting the process?  The first time it runs, it can take a while to start up (try 20 seconds).  It gets snappier after that.

Try some things for me:

In Swan Console:
1.  `rm /tmp/.X* -r`  This will remove the lock file that X produces.  It prevents startup if X is running, but isn't removed if X is killed.
2.  `spm -u && exit`
3.  Wait for cygwin setup to finish.
4.  Try running Xfce4 desktop and waiting a little while, to make sure it just doesn't run slow on your machine.

Let me know if it ever comes up after waiting.  It will produce a window that flashes open then disappears, but should start up after a bit.

**Comment by aagha** [comment] 2017-03-29 17:58
OK, you were right. I let it run for about 2 min and it started--I see the small dock(?) across the top.

That said, no terminals get opened, and I get warnings when I hover or click on any of the items in the dock.

Here are some of the errors:

(xfce4-session:9444): xfce4-session-WARNING **: xfsm_manager_load_session: Something wrong with /cygdrive/c/cygwin/home/amagha//.cache/sessions/xfce4-session-METRICAL#0, Does it exist? Permissions issue?

(gnome-keyring-daemon:13872): GLib-GIO-WARNING **: Problems looking up entry in keyring: Error opening keyring '/cygdrive/c/cygwin/home/amagha/.dbus-keyrings/org_freedesktop_general' for reading: Failed to open file '/cygdrive/c/cygwin/home/amagha/.dbus-keyrings/org_freedesktop_general': No such file or directory
** Message: couldn't connect to dbus session bus: Unexpected lack of content trying to read a line

(process:13624): GLib-WARNING **: /usr/src/ports/glib2.0/glib2.0-2.50.3-1.x86_64/src/glib-2.50.3/glib/gmem.c:483: custom memory allocation vtable not supported

(xfce4-panel:8652): GLib-GIO-WARNING **: Problems looking up entry in keyring: Error opening keyring '/cygdrive/c/cygwin/home/amagha/.dbus-keyrings/org_freedesktop_general' for reading: Failed to open file '/cygdrive/c/cygwin/home/amagha/.dbus-keyrings/org_freedesktop_general': No such file or directory

** (xfsettingsd:4624): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

(xfsettingsd:4624): xfsettingsd-WARNING **: Property "/Gdk/WindowScalingFactor" has an unsupported type "guint".

** (seahorse-daemon:13624): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

(xfsettingsd:4624): GLib-GIO-WARNING **: Problems looking up entry in keyring: Error opening keyring '/cygdrive/c/cygwin/home/amagha/.dbus-keyrings/org_freedesktop_general' for reading: Failed to open file '/cygdrive/c/cygwin/home/amagha/.dbus-keyrings/org_freedesktop_general': No such file or directory

** (xfsettingsd:4408): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
SetupSysMenu: GetSystemMenu() failed for HWND 0x40998

(xfce4-panel:8652): libxfce4ui-WARNING **: ICE I/O Error

(xfce4-panel:8652): libxfce4ui-WARNING **: Disconnected from session manager.

(xfsettingsd:4624): libxfce4ui-WARNING **: ICE I/O Error

(xfsettingsd:4624): libxfce4ui-WARNING **: Disconnected from session manager.
xfsettingsd: No window manager registered on screen 0.
IsOverrideRedirect: Failed to get window attributes
IsOverrideRedirect: Failed to get window attributes
SetupSysMenu: GetSystemMenu() failed for HWND 0x70b66
IsOverrideRedirect: Failed to get window attributes
IsOverrideRedirect: Failed to get window attributes
IsOverrideRedirect: Failed to get window attributes
SetupSysMenu: GetSystemMenu() failed for HWND 0x80b66
IsOverrideRedirect: Failed to get window attributes
IsOverrideRedirect: Failed to get window attributes
SetupSysMenu: GetSystemMenu() failed for HWND 0x90b66
IsOverrideRedirect: Failed to get window attributes
IsOverrideRedirect: Failed to get window attributes
IsOverrideRedirect: Failed to get window attributes
IsOverrideRedirect: Failed to get window attributes
IsOverrideRedirect: Failed to get window attributes
IsOverrideRedirect: Failed to get window attributes
IsOverrideRedirect: Failed to get window attributes
IsOverrideRedirect: Failed to get window attributes
IsOverrideRedirect: Failed to get window attributes
IsOverrideRedirect: Failed to get window attributes
SetupSysMenu: GetSystemMenu() failed for HWND 0xb09b4
IsOverrideRedirect: Failed to get window attributes

** (exo-open:1184): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

** (exo-helper-1:11888): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

(process:10176): GLib-GIO-WARNING **: Problems looking up entry in keyring: Error opening keyring '/cygdrive/c/cygwin/home/amagha/.dbus-keyrings/org_freedesktop_general' for reading: Failed to open file '/cygdrive/c/cygwin/home/amagha/.dbus-keyrings/org_freedesktop_general': No such file or directory
SetupSysMenu: GetSystemMenu() failed for HWND 0x100b66
SetupSysMenu: GetSystemMenu() failed for HWND 0xc0b88
SetupSysMenu: GetSystemMenu() failed for HWND 0x90c2c

(process:9888): GLib-GIO-WARNING **: Problems looking up entry in keyring: Error opening keyring '/cygdrive/c/cygwin/home/amagha/.dbus-keyrings/org_freedesktop_general' for reading: Failed to open file '/cygdrive/c/cygwin/home/amagha/.dbus-keyrings/org_freedesktop_general': No such file or directory

** (exo-open:1328): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

**Comment by isaacwhanson** [comment] 2017-03-29 18:14
#12 marking as duplicate of issue 12.  Please refer to that ticket, and include some system specs (including graphics adapter).  Thanks.

**Comment by isaacwhanson** [comment] 2017-03-29 18:27
Here is a thought.  What Antivirus do you have?  It is possible that dbus-daemon is incorrectly quarantined.

**Comment by aagha** [comment] 2017-03-30 01:32
Standard Windows 10--nothing else.

**Comment by isaacwhanson** [comment] 2017-03-30 02:49
Are you on a Lenovo machine?

**Comment by aagha** [comment] 2017-03-30 04:13
Yes, on a Lenovo.

I'll try some of the things mentioned in the article.

When I launch the Swan console, this is the initial output:

ls: cannot access '/cygdrive/c/cygwin/home/amagha//Desktop': No such file or directory
ls: reading directory '/cygdrive/c/cygwin/home/amagha/': No such file or directory
ls: reading directory '/cygdrive/c/cygwin/home/amagha/': No such file or directory
ls: reading directory '/cygdrive/c/cygwin/home/amagha/': No such file or directory
ls: reading directory '/cygdrive/c/cygwin/home/amagha/': No such file or directory
ls: reading directory '/cygdrive/c/cygwin/home/amagha/': No such file or directory
ls: reading directory '/cygdrive/c/cygwin/home/amagha/': No such file or directory
/cygdrive/c/cygwin/home/amagha//.zshrc:source:61: no such file or directory: /home/amagha/.oh-my-zsh/oh-my-zsh.sh
/cygdrive/c/cygwin/home/amagha//zsh/z.sh:234: failed to load module `zsh/zle': No such file or directory
zsh: failed to load module `zsh/zle': No such file or directory
\[\e]0;\w\a\]\n\[\e[32m\]\u@\h \[\e[33m\]\w\[\e[0m\]\n\$

Also, where's the history on this post? I cant find what you asked me to type to launch the actual console.

**Comment by isaacwhanson** [comment] 2017-03-30 12:22
@aagha  This is a duplicate of (closed) issue #12 .  Please refer to that ticket in the future.

Also, the command you want is `exec /usr/bin/startx /etc/X11/xinit/Xsession xfce`

**Closed** 2017-03-30 12:23 UTC
Labels: bug, duplicate
