### ISSUE TITLE
Opening anything take a long time (between 1-5 minutes)

### ISSUE THREAD

**Issue by IMFUZZ** [starlight/swan-desktop#12] opened 2017-03-23 15:43 UTC
Also, I noticed that opening anything from the "Swan Xfce4 Desktop" takes a very long time to display. The process is opened in background (ex: tunar.exe) but only shows after a couple of minutes. Doesn't seem to use any hardware acceleration, could it be a possible cause of the slow load time?

Here are some system info :
```OS Name	Microsoft Windows 10 Pro
Version	10.0.14393 Build 14393
OS Manufacturer	Microsoft Corporation
System Manufacturer	LENOVO
System Model	20F9CTO1WW
System Type	x64-based PC
System SKU	LENOVO_MT_20F9_BU_Think_FM_ThinkPad T460s
Processor	Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz, 2400 Mhz, 2 Core(s), 4 Logical Processor(s)
BIOS Version/Date	LENOVO N1CET52W (1.20 ), 2016-11-30
```

**Comment by isaacwhanson** [comment] 2017-03-23 15:49
I will look into this, that is not normal behavior - it should be quite snappy.  Swan does try to make use of your system's hardware acceleration - I will have to look into your system's specs.  Thanks for the bug report.

**Comment by isaacwhanson** [comment] 2017-03-23 16:05
Ok, few things.

1. Logout of Swan. Change the Xfce shortcut, removing the `-w hide` option.  Start Xfce, copy the text output from XWin, and post it here.
2. Open Thunar, and close it.  Copy the contents if `~/.xserver-errors` and post it here.
3. Run `pstree` in xfce4-terminal and post it here.

That should help me see what is going on.

**Comment by IMFUZZ** [comment] 2017-03-23 18:10
Should be able to do so within the next 2 hours or so. Thanks for the quick
feedback.

Le 23 mars 2017 12:05 PM, "Isaac W Hanson" <notifications@github.com> a
écrit :

Ok, few things.

   1. Logout of Swan. Change the Xfce shortcut, removing the -w hide
   option. Start Xfce, copy the text output from XWin, and post it here.
   2. Open Thunar, and close it. Copy the contents if ~/.xserver-errors and
   post it here.
   3. Run pstree in xfce4-terminal and post it here.

That should help me see what is going on.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/starlight/swan-desktop/issues/12#issuecomment-288769270>,
or mute the thread

**Comment by isaacwhanson** [comment] 2017-03-23 18:40
Changed instructions.  Forgot I changed the way Xfce launches..

**Comment by IMFUZZ** [comment] 2017-03-23 18:48
No problem!
PS : Tried running ```exec /usr/bin/startx /etc/X11/xinit/Xsession xfce``` directly from the Swan Console and everything was snappy

**Comment by isaacwhanson** [comment] 2017-03-23 18:52
Ok that is weird. It is basically the same thing.  At least you can play around with it for now until we can look into it more.

**Comment by IMFUZZ** [comment] 2017-03-23 18:54
I'll post the content of the log files soon, just waiting on Swan-Xfce4-Desktop to open... 😅

**Comment by isaacwhanson** [comment] 2017-03-23 18:55
lol no rush.  I may not get to look at it for a couple hours anyway (got the day job ;)

**Comment by IMFUZZ** [comment] 2017-03-23 19:18
[swan_logs.txt](https://github.com/starlight/swan-desktop/files/865901/swan_logs.txt)

**Comment by IMFUZZ** [comment] 2017-03-23 19:19
There's a section at the end for the .xsession-errors content

**Comment by isaacwhanson** [comment] 2017-03-23 19:50
were you able to run `pstree`? I suspect that `gam_server` processes are crashing..

**Comment by isaacwhanson** [comment] 2017-03-23 20:44
if you have time, I would like you to try making a copy of your Xfce shortcut and change it to run:

`C:\.swan-x86_64\bin\mintty.exe /bin/sh.exe -l -c "startxfce4"`

If that is snappy for you, I will make it the default shortcut (after some testing)

**Comment by JokerQyou** [comment] 2017-03-24 06:57
I'm seeing this as well. Here is the content of `/var/log/xwin/xwin.0.log`:

```log
Welcome to the XWin X Server
Vendor: The Cygwin/X Project
Release: 1.19.2.0
OS: CYGWIN_NT-10.0 Joker-Windows 2.7.0(0.306/5/3) 2017-02-12 13:18 x86_64
OS: Windows 10  [Windows NT 10.0 build 14393] (Win64)
Package: version 1.19.2-1 built 2017-03-09

XWin was started with the following command line:

X :0 -multiwindow -multimonitors -resize=randr -notrayicon 
 -nokeyhook -unixkill -nowinkill -compositewm -noprimary 

ddxProcessArgument - Initializing default screens
winInitializeScreenDefaults - primary monitor w 1920 h 1080
winInitializeScreenDefaults - native DPI x 96 y 96
[236046.500] (II) xorg.conf is not supported
[236046.500] (II) See http://x.cygwin.com/docs/faq/cygwin-x-faq.html for more information
[236046.500] LoadPreferences: /cygdrive/c/Users/Joker Qyou/.XWinrc not found
[236046.500] LoadPreferences: Loading /etc/X11/system.XWinrc
[236046.515] LoadPreferences: Done parsing the configuration file...
[236046.515] winDetectSupportedEngines - RemoteSession: no
[236046.671] winDetectSupportedEngines - DirectDraw4 installed, allowing ShadowDDNL
[236046.687] winDetectSupportedEngines - Returning, supported engines 00000005
[236046.703] winSetEngine - Multi Window or Rootless => ShadowGDI
[236046.703] winScreenInit - Using Windows display depth of 32 bits per pixel
[236046.734] winAllocateFBShadowGDI - Creating DIB with width: 3286 height: 1216 depth: 32
[236046.734] winFinishScreenInitFB - Masks: 00ff0000 0000ff00 000000ff
[236046.734] winInitVisualsShadowGDI - Masks 00ff0000 0000ff00 000000ff BPRGB 8 d 24 bpp 32
[236046.734] MIT-SHM extension disabled due to lack of kernel support
[236046.734] XFree86-Bigfont extension local-client optimization disabled due to lack of shared memory support in the kernel
[236046.734] glWinSelectGLimplementation: Loaded 'cygnativeGLthunk.dll'
[236047.796] (II) AIGLX: Testing pixelFormatIndex 5
[236047.968] GL_VERSION:     4.5.0 NVIDIA 378.66
[236047.968] GL_VENDOR:      NVIDIA Corporation
[236047.968] GL_RENDERER:    GeForce GT 540M/PCIe/SSE2
[236047.968] (II) GLX: enabled GLX_SGI_make_current_read
[236047.968] (II) GLX: enabled GLX_SGI_swap_control
[236047.968] (II) GLX: enabled GLX_MESA_swap_control
[236047.968] (II) GLX: enabled GLX_SGIX_pbuffer
[236047.968] (II) GLX: enabled GLX_ARB_multisample
[236047.968] (II) GLX: enabled GLX_SGIS_multisample
[236047.968] (II) GLX: enabled GLX_ARB_fbconfig_float
[236047.968] (II) GLX: enabled GLX_EXT_fbconfig_packed_float
[236047.968] (II) GLX: enabled GLX_ARB_create_context
[236047.968] (II) GLX: enabled GLX_ARB_create_context_profile
[236047.968] (II) GLX: enabled GLX_ARB_create_context_robustness
[236047.968] (II) GLX: enabled GLX_EXT_create_context_es2_profile
[236047.968] (II) AIGLX: enabled GLX_MESA_copy_sub_buffer
[236047.968] (II) 718 pixel formats reported by wglGetPixelFormatAttribivARB
[236048.093] (II) 682 fbConfigs
[236048.093] (II) ignored pixel formats: 0 not OpenGL, 0 unknown pixel type, 36 unaccelerated
[236048.093] (II) GLX: Initialized Win32 native WGL GL provider for screen 0
[236048.484] winPointerWarpCursor - Discarding first warp: 1643 608
[236048.484] (--) 8 mouse buttons found
[236048.484] (--) Setting autorepeat to delay=500, rate=31
[236048.484] (--) Windows keyboard layout: "00000409" (00000409) "US", type 7
[236048.484] (--) Found matching XKB configuration "English (USA)"
[236048.484] (--) Model = "pc105" Layout = "us" Variant = "none" Options = "none"
[236048.484] Rules = "base" Model = "pc105" Layout = "us" Variant = "none" Options = "none"
[236048.484] winInitMultiWindowWM - DISPLAY=:0.0
[236048.484] winMultiWindowXMsgProc - DISPLAY=:0.0
[236048.546] winClipboardThreadProc - DISPLAY=:0.0
[236048.546] winProcEstablishConnection - winInitClipboard returned.
[236048.546] winMultiWindowXMsgProc - xcb_connect() returned and successfully opened the display.
[236048.546] winInitMultiWindowWM - xcb_connect () returned and successfully opened the display.
[236048.546] OS maintains clipboard viewer chain: yes
[236048.546] Using Composite redirection
[236048.546] winClipboardProc - XOpenDisplay () returned and successfully opened the display.
[236300.500] SetupSysMenu: GetSystemMenu() failed for HWND 0x571626
[236312.531] SetupSysMenu: GetSystemMenu() failed for HWND 0x3a1490
[236312.828] SetupSysMenu: GetSystemMenu() failed for HWND 0x1330340
[236314.796] SetupSysMenu: GetSystemMenu() failed for HWND 0xff1016
[236332.390] SetupSysMenu: GetSystemMenu() failed for HWND 0x3017ae
[236333.359] SetupSysMenu: GetSystemMenu() failed for HWND 0x3117ae
[236344.265] SetupSysMenu: GetSystemMenu() failed for HWND 0x3b1490
[236344.312] SetupSysMenu: GetSystemMenu() failed for HWND 0x1340340
[236345.656] SetupSysMenu: GetSystemMenu() failed for HWND 0x3217ae
[236589.250] OS has icon alpha channel support: yes
[236843.453] SetupSysMenu: GetSystemMenu() failed for HWND 0x3517a2
[236871.515] SetupSysMenu: GetSystemMenu() failed for HWND 0x260ba8
[236883.781] SetupSysMenu: GetSystemMenu() failed for HWND 0x280ba8
[236884.687] SetupSysMenu: GetSystemMenu() failed for HWND 0x290ba8
[236884.859] SetupSysMenu: GetSystemMenu() failed for HWND 0x2a0ba8
[236885.015] SetupSysMenu: GetSystemMenu() failed for HWND 0x2b0ba8
[236903.406] IsOverrideRedirect: Failed to get window attributes
[236903.468] SetupSysMenu: GetSystemMenu() failed for HWND 0x480d86
[236906.921] SetupSysMenu: GetSystemMenu() failed for HWND 0x320ba8
[236925.546] IsOverrideRedirect: Failed to get window attributes
[236925.578] SetupSysMenu: GetSystemMenu() failed for HWND 0x2a0e54
[236925.578] IsOverrideRedirect: Failed to get window attributes
[236970.062] IsOverrideRedirect: Failed to get window attributes
[236970.078] IsOverrideRedirect: Failed to get window attributes
[236970.093] IsOverrideRedirect: Failed to get window attributes
[236970.093] SetupSysMenu: GetSystemMenu() failed for HWND 0xad1794
[237052.578] SetupSysMenu: GetSystemMenu() failed for HWND 0x2318a2
[237059.671] SetupSysMenu: GetSystemMenu() failed for HWND 0x1f0314
[237078.546] IsOverrideRedirect: Failed to get window attributes
[237078.546] IsOverrideRedirect: Failed to get window attributes
[237078.562] IsOverrideRedirect: Failed to get window attributes
[237078.562] SetupSysMenu: GetSystemMenu() failed for HWND 0x731a9e
[237168.968] IsOverrideRedirect: Failed to get window attributes
[237168.984] SetupSysMenu: GetSystemMenu() failed for HWND 0x230710
[237169.296] IsOverrideRedirect: Failed to get window attributes
[237169.296] IsOverrideRedirect: Failed to get window attributes
[237169.953] IsOverrideRedirect: Failed to get window attributes
[237170.062] IsOverrideRedirect: Failed to get window attributes
[237170.296] IsOverrideRedirect: Failed to get window attributes
[237170.312] IsOverrideRedirect: Failed to get window attributes
[237170.390] IsOverrideRedirect: Failed to get window attributes
[237170.406] IsOverrideRedirect: Failed to get window attributes
[237170.406] IsOverrideRedirect: Failed to get window attributes
[237170.421] IsOverrideRedirect: Failed to get window attributes
[237170.437] IsOverrideRedirect: Failed to get window attributes
[237170.937] SetupSysMenu: GetSystemMenu() failed for HWND 0xad1ade
[237170.937] IsOverrideRedirect: Failed to get window attributes
[237171.250] IsOverrideRedirect: Failed to get window attributes
[237171.953] IsOverrideRedirect: Failed to get window attributes
[237173.984] IsOverrideRedirect: Failed to get window attributes
[237174.000] SetupSysMenu: GetSystemMenu() failed for HWND 0x79133e
[237174.000] IsOverrideRedirect: Failed to get window attributes
[237178.437] IsOverrideRedirect: Failed to get window attributes
[237178.468] SetupSysMenu: GetSystemMenu() failed for HWND 0xa61766
[237178.468] IsOverrideRedirect: Failed to get window attributes
[237178.859] IsOverrideRedirect: Failed to get window attributes
[237178.859] SetupSysMenu: GetSystemMenu() failed for HWND 0xac1766
[237178.906] IsOverrideRedirect: Failed to get window attributes
[237178.906] IsOverrideRedirect: Failed to get window attributes
[237179.031] IsOverrideRedirect: Failed to get window attributes
[237179.046] IsOverrideRedirect: Failed to get window attributes
[237179.156] IsOverrideRedirect: Failed to get window attributes
[237179.250] IsOverrideRedirect: Failed to get window attributes
[237179.250] IsOverrideRedirect: Failed to get window attributes
[237179.250] SetupSysMenu: GetSystemMenu() failed for HWND 0xad1766
[237179.625] IsOverrideRedirect: Failed to get window attributes
[237179.812] IsOverrideRedirect: Failed to get window attributes
[237180.031] IsOverrideRedirect: Failed to get window attributes
[237180.031] SetupSysMenu: GetSystemMenu() failed for HWND 0xae1766
[237180.046] IsOverrideRedirect: Failed to get window attributes
[237180.046] IsOverrideRedirect: Failed to get window attributes
[237180.062] IsOverrideRedirect: Failed to get window attributes
[237180.062] IsOverrideRedirect: Failed to get window attributes
[237180.203] IsOverrideRedirect: Failed to get window attributes
[237180.375] IsOverrideRedirect: Failed to get window attributes
[237180.375] IsOverrideRedirect: Failed to get window attributes
[237180.375] IsOverrideRedirect: Failed to get window attributes
[237181.343] IsOverrideRedirect: Failed to get window attributes
[237181.875] IsOverrideRedirect: Failed to get window attributes
[237181.875] SetupSysMenu: GetSystemMenu() failed for HWND 0xaf1766
[237181.875] IsOverrideRedirect: Failed to get window attributes
[237181.890] IsOverrideRedirect: Failed to get window attributes
[237182.343] IsOverrideRedirect: Failed to get window attributes
[237182.453] IsOverrideRedirect: Failed to get window attributes
[237183.078] IsOverrideRedirect: Failed to get window attributes
[237187.531] SetupSysMenu: GetSystemMenu() failed for HWND 0x3f1a24
[237187.578] SetupSysMenu: GetSystemMenu() failed for HWND 0x2f0e9a
[237260.250] SetupSysMenu: GetSystemMenu() failed for HWND 0x6b113a
[237260.281] SetupSysMenu: GetSystemMenu() failed for HWND 0x57103a

```

And there is no such file as `~/.xserver-errors`, there is only a `~/.xsession-errors` file and its contents are:

```log
/etc/X11/xinit/xinitrc-common: 第 20 行:[: /cygdrive/c/Users/Joker: 需要二元表达式
/home/Joker Qyou/桌面 was removed, reassigning DESKTOP to homedir
/home/Joker Qyou/下载 was removed, reassigning DOWNLOAD to homedir
/home/Joker Qyou/模板 was removed, reassigning TEMPLATES to homedir
/home/Joker Qyou/公共 was removed, reassigning PUBLICSHARE to homedir
/home/Joker Qyou/文档 was removed, reassigning DOCUMENTS to homedir
/home/Joker Qyou/音乐 was removed, reassigning MUSIC to homedir
/home/Joker Qyou/图片 was removed, reassigning PICTURES to homedir
/home/Joker Qyou/视频 was removed, reassigning VIDEOS to homedir
/usr/bin/startxfce4: X server already running on display :0
/usr/bin/startxfce4: 第 111 行:[: /cygdrive/c/Users/Joker: 需要二元表达式
/usr/bin/startxfce4: 第 113 行:[: /cygdrive/c/Users/Joker: 需要二元表达式
/etc/xdg/xfce4/xinitrc: 第 67 行:test: /cygdrive/c/Users/Joker: 需要二元表达式
/etc/xdg/xfce4/xinitrc: 第 88 行:test: /cygdrive/c/Users/Joker: 需要二元表达式
xfce4-session: No GPG agent found

(xfce4-session:19692): xfce4-session-WARNING **: xfsm_manager_load_session: Something wrong with /cygdrive/c/Users/Joker Qyou/.cache/sessions/xfce4-session-Joker-Windows#0, Does it exist? Permissions issue?
env: "xfwm4": No such file or directory
env: "xfdesktop": No such file or directory

(process:7296): GLib-WARNING **: /usr/src/ports/glib2.0/glib2.0-2.50.3-1.x86_64/src/glib-2.50.3/glib/gmem.c:483: custom memory allocation vtable not supported

(xfsettingsd:10588): GLib-GIO-WARNING **: Problems looking up entry in keyring: 目录“/cygdrive/c/Users/Joker Qyou/.dbus-keyrings”权限错误。期望 0700，得到 0770
xfce4-panel: No window manager registered on screen 0. To start the panel without this check, run with --disable-wm-check.

(xfce4-panel:5944): GLib-GIO-WARNING **: Problems looking up entry in keyring: 目录“/cygdrive/c/Users/Joker Qyou/.dbus-keyrings”权限错误。期望 0700，得到 0770

** (seahorse-daemon:7296): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
xfsettingsd: No window manager registered on screen 0.

(xfce4-panel:5944): Gtk-CRITICAL **: gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed

(xfce4-panel:5944): Gtk-CRITICAL **: gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed

(xfce4-panel:5944): Gtk-CRITICAL **: gtk_widget_show: assertion 'GTK_IS_WIDGET (widget)' failed

(Thunar:18900): GLib-GIO-WARNING **: Problems looking up entry in keyring: 目录“/cygdrive/c/Users/Joker Qyou/.dbus-keyrings”权限错误。期望 0700，得到 0770

(xfce4-settings-manager:21116): GLib-GIO-WARNING **: Problems looking up entry in keyring: 目录“/cygdrive/c/Users/Joker Qyou/.dbus-keyrings”权限错误。期望 0700，得到 0770

(thunar:12088): GLib-GIO-WARNING **: Problems looking up entry in keyring: 目录“/cygdrive/c/Users/Joker Qyou/.dbus-keyrings”权限错误。期望 0700，得到 0770

(Thunar:18900): GLib-GIO-WARNING **: Problems looking up entry in keyring: 目录“/cygdrive/c/Users/Joker Qyou/.dbus-keyrings”权限错误。期望 0700，得到 0770

(thunar:12088): GLib-GIO-WARNING **: Problems looking up entry in keyring: 目录“/cygdrive/c/Users/Joker Qyou/.dbus-keyrings”权限错误。期望 0700，得到 0770

(xfce4-display-settings:22488): GLib-GIO-WARNING **: Problems looking up entry in keyring: 目录“/cygdrive/c/Users/Joker Qyou/.dbus-keyrings”权限错误。期望 0700，得到 0770

(process:21832): GLib-GIO-WARNING **: Problems looking up entry in keyring: 目录“/cygdrive/c/Users/Joker Qyou/.dbus-keyrings”权限错误。期望 0700，得到 0770

** (xfce4-terminal:21832): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

(xfce4-terminal:21832): GLib-GIO-WARNING **: Problems looking up entry in keyring: 目录“/cygdrive/c/Users/Joker Qyou/.dbus-keyrings”权限错误。期望 0700，得到 0770

(process:18156): GLib-GIO-WARNING **: Problems looking up entry in keyring: 目录“/cygdrive/c/Users/Joker Qyou/.dbus-keyrings”权限错误。期望 0700，得到 0770

(xfce4-terminal:21832): GLib-GIO-WARNING **: Problems looking up entry in keyring: 目录“/cygdrive/c/Users/Joker Qyou/.dbus-keyrings”权限错误。期望 0700，得到 0770

** (xfce4-terminal:18156): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

(xfce4-terminal:18156): GLib-GIO-WARNING **: Problems looking up entry in keyring: 目录“/cygdrive/c/Users/Joker Qyou/.dbus-keyrings”权限错误。期望 0700，得到 0770

(xfce4-terminal:18156): GLib-GIO-WARNING **: Problems looking up entry in keyring: 目录“/cygdrive/c/Users/Joker Qyou/.dbus-keyrings”权限错误。期望 0700，得到 0770
```

Basically it complaints about some misconfiguration at the start (but I don't know which file it was reading), and some permission errors.

And here is the result of `pstree` command in xfce terminal:

```
$ pstree
?─┬─Thunar
  ├─dbus-daemon
  ├─dbus-launch
  ├─gam_server
  ├─seahorse-daemon
  ├─sh───xinit─┬─XWin
  │            └─sh───xfce4-session───xfce4-notifyd
  ├─ssh-agent
  ├─xfce4-display-set
  ├─xfce4-panel───wrapper-1.0
  ├─xfce4-terminal
  ├─xfce4-terminal───bash───pstree
  ├─xfconfd
  └─xfsettingsd

```

Besides the extremely slow speed, all the windows look just like native Windows 10 windows, with no decorations like the screenshots from the project home page.

**Comment by isaacwhanson** [comment] 2017-03-24 13:14
I think I see the issue, will try to put out a fix very soon.. In the screenshot on the site I am using Windows decorations, just with gray color.

**Comment by isaacwhanson** [comment] 2017-03-24 15:41
@IMFUZZ Does your username have a space in it?

**Comment by IMFUZZ** [comment] 2017-03-24 16:28
Nope

Le 24 mars 2017 11:41 AM, "Isaac W Hanson" <notifications@github.com> a
écrit :

**Comment by isaacwhanson** [comment] 2017-03-24 19:51
@IMFUZZ @JokerQyou Did either of you install into existing Cygwin?

**Comment by isaacwhanson** [comment] 2017-03-24 20:50
@JokerQyou does it work OK if you run command `exec /usr/bin/startx /etc/X11/xinit/Xsession xfce` from Swan Console ?

**Comment by IMFUZZ** [comment] 2017-03-24 22:18
I may have had Cygwin on my machine before installing Swan

Le 24 mars 2017 3:51 PM, "Isaac W Hanson" <notifications@github.com> a
écrit :

@IMFUZZ <https://github.com/IMFUZZ> @JokerQyou
<https://github.com/JokerQyou> Did either of you install into existing
Cygwin?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/starlight/swan-desktop/issues/12#issuecomment-289126805>,
or mute the thread

**Comment by IMFUZZ** [comment] 2017-03-24 22:19
Not 100% sure thought

**Comment by isaacwhanson** [comment] 2017-03-24 22:50
@JokerQyou Your problem is probably the spaces in your username.

https://github.com/starlight/swan-desktop/issues/18

**Comment by isaacwhanson** [comment] 2017-03-24 22:53
@IMFUZZ I updated some things.  Logout out of Swan Desktop, Open Swan Console.

run: `killall gam_server; spm -u && exit`

When Cygwin update finishes, try out Swan Desktop.  Let me know if still having issues.  Sorry I can't be more precise, I am unable to replicate your issue currently, but I have some ideas..

**Comment by JokerQyou** [comment] 2017-03-25 08:56
I cannot be sure of wether I have Cygwin installed or not. I've never installed Cygwin manually before, but I'm using a mixed bunch of tools which might have part of Cygwin or MingW, includes win-bash, cmder and Babun.

Running `exec /usr/bin/startx /etc/X11/xinit/Xsession xfce` directly in Swan console does not help. I'll try the update in Monday, cause my computer is not here with me at home.

**Comment by isaacwhanson** [comment] 2017-03-25 13:32
@JokerQyou Your problem is probably the spaces in your username.  Please see https://github.com/starlight/swan-desktop/issues/18

**Comment by isaacwhanson** [comment] 2017-03-28 23:25
@IMFUZZ is this still an issue after upgrading?

**Comment by isaacwhanson** [comment] 2017-03-30 02:48
Some Lenovo software conflicts with Cygwin.  Among these are "Lenovo IPS Core Service (ipssvc)" and "Lenovo RapidBoot Shield".  I believe this to be the cause of your troubles @IMFUZZ 

https://cygwin.com/faq/faq.html#faq.using.bloda

**Closed** 2017-03-30 03:28 UTC
Labels: bug
