### ISSUE TITLE
Something wrong with python

### ISSUE THREAD

**Issue by YuyangZhangFTD** [starlight/swan-desktop#21] opened 2017-03-25 17:16 UTC
Hey, I installed some packages of python on swan console, using 'spm -i python-numpy' or pip. And when I enter python, and import numpy, it shows 'No such file or directory',,, 
How to solve it? :P

**Comment by SharkWipf** [comment] 2017-03-25 17:23
Haven't tried this myself yet, but could it be you also have the native
Windows version of Python installed?
Windows paths are checked before Cygwin/Swan paths I believe, so you might
accidentally be running the Windows version of Python if so.
I'd suggest running "which python" and see if it uses the right Python.

**Comment by isaacwhanson** [comment] 2017-03-25 18:16
Yeah, I would check your $PATH environment variable, it will show you where it is looking for python, in order.  You can change your $PATH variable in your `~/.bashrc` and it will affect only your Swan installation.

Or you can try using your Swan installation of python directly by specifying the path: `/usr/bin/python my_script.py`

**Comment by isaacwhanson** [comment] 2017-03-25 18:22
> Isaac@DESKTOP-DCJ8PMQ ~
> $ python ./test.py 
> Help on package numpy:
> 
> NAME
>     numpy
> 
> FILE
>     /usr/lib/python2.7/site-packages/numpy/__init__.py
> 
> DESCRIPTION
>     NumPy
> 
Seems to work fine for me, seems to be an issue with your PATH.  Closing as unable to reproduce.

**Closed by isaacwhanson** 2017-03-25 18:22 UTC
Labels: bug
