### ISSUE TITLE
Lynx didn't install with base

### ISSUE THREAD

**Issue by wd5gnr** [starlight/swan-desktop#19] opened 2017-03-25 02:04 UTC
Installed swan-base and then tried to run spm but lynx was not installed. Copied lynx.exe from my cygwin directory along with /etc/lynx* and that seems to have solved it. Don't know why it didn't get installed and have not tried to reproduce it.

**Comment by isaacwhanson** [comment] 2017-03-25 02:38
Ah yes, `lynx` used to be a cygwin base package.  I will update it, thanks for the report.

**Comment by isaacwhanson** [comment] 2017-03-25 03:37
it should have used `lynx` only as a fallback if it could not find `wget`, bet that is a dependency of `swan-base` via the `cygport` dependency.  Not sure why wget did not get installed,   Closing this as unable to reproduce.

**Closed by isaacwhanson** 2017-03-25 03:37 UTC
Labels: bug

**Comment by wd5gnr** [comment] 2017-03-25 11:02
Turns out wget is identified by Cisco AMP as a virus and quarantined. So that explains it.
